// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: dispatcher.proto

package ring

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CacheDispatcher_DispatchGet_FullMethodName    = "/ring.CacheDispatcher/DispatchGet"
	CacheDispatcher_DispatchSet_FullMethodName    = "/ring.CacheDispatcher/DispatchSet"
	CacheDispatcher_DispatchDelete_FullMethodName = "/ring.CacheDispatcher/DispatchDelete"
)

// CacheDispatcherClient is the client API for CacheDispatcher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CacheDispatcherClient interface {
	DispatchGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	DispatchSet(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	DispatchDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type cacheDispatcherClient struct {
	cc grpc.ClientConnInterface
}

func NewCacheDispatcherClient(cc grpc.ClientConnInterface) CacheDispatcherClient {
	return &cacheDispatcherClient{cc}
}

func (c *cacheDispatcherClient) DispatchGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, CacheDispatcher_DispatchGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheDispatcherClient) DispatchSet(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, CacheDispatcher_DispatchSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheDispatcherClient) DispatchDelete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, CacheDispatcher_DispatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheDispatcherServer is the server API for CacheDispatcher service.
// All implementations should embed UnimplementedCacheDispatcherServer
// for forward compatibility
type CacheDispatcherServer interface {
	DispatchGet(context.Context, *GetRequest) (*GetResponse, error)
	DispatchSet(context.Context, *SetRequest) (*SetResponse, error)
	DispatchDelete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedCacheDispatcherServer should be embedded to have forward compatible implementations.
type UnimplementedCacheDispatcherServer struct {
}

func (UnimplementedCacheDispatcherServer) DispatchGet(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchGet not implemented")
}
func (UnimplementedCacheDispatcherServer) DispatchSet(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchSet not implemented")
}
func (UnimplementedCacheDispatcherServer) DispatchDelete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DispatchDelete not implemented")
}

// UnsafeCacheDispatcherServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CacheDispatcherServer will
// result in compilation errors.
type UnsafeCacheDispatcherServer interface {
	mustEmbedUnimplementedCacheDispatcherServer()
}

func RegisterCacheDispatcherServer(s grpc.ServiceRegistrar, srv CacheDispatcherServer) {
	s.RegisterService(&CacheDispatcher_ServiceDesc, srv)
}

func _CacheDispatcher_DispatchGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheDispatcherServer).DispatchGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheDispatcher_DispatchGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheDispatcherServer).DispatchGet(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheDispatcher_DispatchSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheDispatcherServer).DispatchSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheDispatcher_DispatchSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheDispatcherServer).DispatchSet(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CacheDispatcher_DispatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheDispatcherServer).DispatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CacheDispatcher_DispatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheDispatcherServer).DispatchDelete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CacheDispatcher_ServiceDesc is the grpc.ServiceDesc for CacheDispatcher service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CacheDispatcher_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ring.CacheDispatcher",
	HandlerType: (*CacheDispatcherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DispatchGet",
			Handler:    _CacheDispatcher_DispatchGet_Handler,
		},
		{
			MethodName: "DispatchSet",
			Handler:    _CacheDispatcher_DispatchSet_Handler,
		},
		{
			MethodName: "DispatchDelete",
			Handler:    _CacheDispatcher_DispatchDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dispatcher.proto",
}
