import { css } from '@emotion/css';

import { SceneComponentProps, SceneObjectBase, SceneObjectState } from '@grafana/scenes';
import { useStyles2 } from '@grafana/ui';

interface ImageState extends SceneObjectState {
  url: string;
}

export class Image extends SceneObjectBase<ImageState> {
  public static Component = ImageRenderer;
}

function ImageRenderer({ model }: SceneComponentProps<Image>) {
  const { url } = model.useState();
  const styles = useStyles2(getStyles);

  return <img className={styles.image} src={url} alt="Something generated by AI" />;
}

const getStyles = () => ({
  image: css({
    label: 'dash-message-image',
  }),
});
