import { SceneComponentProps, SceneObjectBase, SceneObjectState } from '@grafana/scenes';

interface ImageState extends SceneObjectState {
  url: string;
}

export class Image extends SceneObjectBase<ImageState> {
  public static Component = ImageRenderer;
}

function ImageRenderer({ model }: SceneComponentProps<Image>) {
  const { url } = model.useState();

  return <img src={url} alt="Something generated by AI" />;
}
