//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaTempRoleBinding = resource.NewSimpleSchema("iam2.grafana.app", "v0alpha1", &TempRoleBinding{}, &TempRoleBindingList{}, resource.WithKind("TempRoleBinding"),
		resource.WithPlural("temprolebindings"), resource.WithScope(resource.NamespacedScope))
	kindTempRoleBinding = resource.Kind{
		Schema: schemaTempRoleBinding,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &TempRoleBindingJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func TempRoleBindingKind() resource.Kind {
	return kindTempRoleBinding
}

// Schema returns a resource.SimpleSchema representation of TempRoleBinding
func TempRoleBindingSchema() *resource.SimpleSchema {
	return schemaTempRoleBinding
}

// Interface compliance checks
var _ resource.Schema = kindTempRoleBinding
