// Generated by ts-to-zod
import { z } from 'zod';

const kindSchema = z.any();

const dashboardCursorSyncSchema = z.any();

const dashboardLinkSchema = z.any();

const timeSettingsSpecSchema = z.any();

const queryVariableKindSchema = z.any();

const textVariableKindSchema = z.any();

const referenceableSchema = z.any();

const annotationQueryKindSchema = z.any();

const gridLayoutKindSchema = z.any();

export const dashboardV2Schema = kindSchema;

const dashboardSpecSchema = z.object({
  id: z.number().optional(),
  title: z.string(),
  description: z.string(),
  cursorSync: dashboardCursorSyncSchema,
  liveNow: z.boolean(),
  preload: z.boolean(),
  editable: z.boolean(),
  links: z.array(dashboardLinkSchema),
  tags: z.array(z.string()),
  timeSettings: timeSettingsSpecSchema,
  variables: z.array(z.union([queryVariableKindSchema, textVariableKindSchema])),
  elements: referenceableSchema,
  annotations: z.array(annotationQueryKindSchema),
  layout: gridLayoutKindSchema,
});
