// Generated by ts-to-zod
import { z } from 'zod';

export const queryOptionsSpecSchema = z.object({
  timeFrom: z.string().optional(),
  maxDataPoints: z.number().optional(),
  timeShift: z.string().optional(),
  queryCachingTTL: z.number().optional(),
  interval: z.string().optional(),
  cacheTimeout: z.string().optional(),
});

export const queryVariableSpecSchema = z.object({});

export const textVariableSpecSchema = z.object({});

export const timeSettingsSpecSchema = z.object({
  timezone: z.string(),
  from: z.string(),
  to: z.string(),
  autoRefresh: z.string(),
  autoRefreshIntervals: z.array(z.string()),
  quickRanges: z.array(z.string()),
  hideTimepicker: z.boolean(),
  weekStart: z.string(),
  fiscalYearStartMonth: z.number(),
  nowDelay: z.string().optional(),
});

const fieldConfigSourceSchema = z.any();

const kindSchema = z.any();

const dataSourceRefSchema = z.any();

const annotationPanelFilterSchema = z.any();

const referenceSchema = z.any();

const dashboardLinkSchema = z.any();

export const vizConfigSpecSchema = z.object({
  pluginVersion: z.string(),
  options: z.record(z.unknown()),
  fieldConfig: fieldConfigSourceSchema,
});

export const vizConfigKindSchema = kindSchema;

const dataQueryKindSchema = kindSchema;

export const annotationQueryKindSchema = kindSchema;

const panelQuerySpecSchema = z.object({
  query: dataQueryKindSchema,
  datasource: dataSourceRefSchema,
  refId: z.string(),
  hidden: z.boolean(),
});

const panelQueryKindSchema = kindSchema;

const transformationKindSchema = kindSchema;

export const queryGroupSpecSchema = z.object({
  queries: z.array(panelQueryKindSchema),
  transformations: z.array(transformationKindSchema),
  queryOptions: queryOptionsSpecSchema,
});

export const queryGroupKindSchema = kindSchema;

export const queryVariableKindSchema = kindSchema;

export const textVariableKindSchema = kindSchema;

const gridLayoutItemSpecSchema = z.object({
  x: z.number(),
  y: z.number(),
  width: z.number(),
  height: z.number(),
  element: referenceSchema,
});

export const gridLayoutItemKindSchema = kindSchema;

export const gridLayoutSpecSchema = z.object({
  items: z.array(gridLayoutItemKindSchema),
});

export const gridLayoutKindSchema = kindSchema;

const panelSpecSchema = z.object({
  uid: z.string(),
  title: z.string(),
  description: z.string(),
  links: z.array(dashboardLinkSchema),
  data: queryGroupKindSchema,
  vizConfig: vizConfigKindSchema,
});

export const panelKindSchema = kindSchema;

const annotationQuerySpecSchema = z.object({
  datasource: dataSourceRefSchema,
  query: dataQueryKindSchema,
  enable: z.boolean(),
  filter: annotationPanelFilterSchema,
  hide: z.boolean(),
  iconColor: z.string(),
  name: z.string(),
});
