import { tool } from '@langchain/core/tools';
import { lastValueFrom } from 'rxjs';
import { z } from 'zod';

import { CoreApp, dateTime, makeTimeRange } from '@grafana/data';
import { getDataSourceSrv } from '@grafana/runtime';
import { LokiDatasource } from 'app/plugins/datasource/loki/datasource';
import { LokiQuery, LokiQueryType } from 'app/plugins/datasource/loki/types';

import { summarizeLokiQueryResult } from './lokiQuerySummarizer';
import { lokiTypeRefiner, unixTimestampRefiner } from './refiners';

const lokiRangeQuerySchema = z.object({
  datasource_uid: z
    .string()
    .describe('The datasource UID, only supports Loki datasource')
    .refine(lokiTypeRefiner.func, lokiTypeRefiner.message),
  query: z.string().describe('(REQUIRED) The LogQL query to execute'),
  start: z
    .number()
    .describe('Start timestamp for the query range (Unix millisecond timestamp)')
    .refine(unixTimestampRefiner.func, unixTimestampRefiner.message),
  end: z
    .number()
    .describe('End timestamp for the query range (Unix millisecond timestamp)')
    .refine(unixTimestampRefiner.func, unixTimestampRefiner.message),
  limit: z
    .number()
    .optional()
    .default(100)
    .describe(
      'Maximum number of log lines to return (for log queries only, default is 100). This is is the only way to limit the number of logs in LogQL. | limit 100 is not valid in LogQL.'
    ),
  summarize: z
    .string()
    .optional()
    .describe(
      'Optional intent for summarization. If provided, returns a summary of the query results instead of the raw data. Example: "Summarize error patterns in logs" or "Identify traffic spikes in metrics"'
    ),
  title: z.string().describe('The title of the query.'),
  description: z.string().describe('The description of the query.'),
});

export const lokiRangeQueryTool = tool(
  async (input) => {
    const parsedInput = lokiRangeQuerySchema.parse(input);
    const { datasource_uid, query, start, end, limit, summarize } = parsedInput;

    // Get datasource
    const datasource = await getDataSourceSrv().get({ uid: datasource_uid });
    if (!datasource) {
      throw new Error(`Datasource with uid ${datasource_uid} not found`);
    }
    const lokiDatasource = datasource as LokiDatasource;

    // Set up time range
    const timeRange = makeTimeRange(dateTime(start), dateTime(end));

    // Detect if this is likely a logs query or a metric query
    const isLikelyLogsQuery =
      !query.includes('rate(') &&
      !query.includes('sum(') &&
      !query.includes('avg(') &&
      !query.includes('max(') &&
      !query.includes('min(') &&
      !query.includes('count(') &&
      !query.includes('quantile(') &&
      !query.includes('stddev(') &&
      !query.includes('stdvar(');

    // Set up the query object
    const lokiQuery: LokiQuery = {
      expr: query,
      refId: 'A',
      queryType: isLikelyLogsQuery ? LokiQueryType.Range : LokiQueryType.Range,
      maxLines: limit,
    };

    // Run query
    const result = await lastValueFrom(
      lokiDatasource.query({
        requestId: '1',
        interval: '1m',
        intervalMs: 60000,
        range: timeRange,
        targets: [lokiQuery],
        scopedVars: {},
        timezone: 'browser',
        app: CoreApp.Explore,
        startTime: timeRange.from.valueOf(),
      })
    );

    // If summarize parameter is provided, use the LLM-based summarizer
    if (summarize) {
      return await summarizeLokiQueryResult('range', query, result, summarize, {
        from: timeRange.from.toISOString(),
        to: timeRange.to.toISOString(),
      });
    }

    // Otherwise return the raw result
    return JSON.stringify(result);
  },
  {
    name: 'loki_range_query',
    description: `
    Execute a Loki range query to evaluate a LogQL expression over a range of time.

    This tool provides two modes of operation:
    1. Data retrieval mode: Returns raw query results as JSON (default)
    2. Summarization mode: When 'summarize' parameter is provided, returns a human-readable summary
       with trend analysis and pattern detection based on the specified intent, generated by an advanced LLM

    This tool can query both logs and metrics from Loki:
    - For logs: Returns matching log lines with timestamps and labels
    - For metrics: Returns time series data for metric queries

    Usage recommendations:
    - When querying or search always try to limit the number of logs returned by 100 or less. Then if you need more increase the limit.
    - For simple log searches, use queries like '{app="myapp"} |= "error"'
    - For metrics, use aggregation operators like 'sum(rate({app="myapp"} |= "error" [5m]))'
    - Use appropriate time ranges to limit data volume
    - Set a reasonable limit for log queries to avoid overwhelming results
    - For complex data, use the summarize parameter to get trend analysis with relevant log examples

    Summarization examples:
    - "Summarize error patterns in the application logs"
    - "Identify any spikes in HTTP error rates"
    - "Analyze response time trends over this period"
    `,
    schema: lokiRangeQuerySchema,
    metadata: {
      explainer: () => {
        return `run Loki range query`;
      },
    },
    verboseParsingErrors: true,
  }
);
